// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: These values are configured for your Firebase project
/// Project ID: youssef-5228c
/// Project number: 293546416514
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web Firebase configuration
  ///
  /// IMPORTANT: These are your actual Firebase configuration values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvsWX4Ajo-LfKYMCp4rPmOwlC08x8P8g',
    appId: '1:293546416514:web:92d97760e6ec2ba574179b',
    messagingSenderId: '293546416514',
    projectId: 'youssef-5228c',
    authDomain: 'youssef-5228c.firebaseapp.com',
    storageBucket: 'youssef-5228c.firebasestorage.app',
    measurementId: 'G-FDHWWLKL92',
  );

  /// Android Firebase configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvsWX4Ajo-LfKYMCp4rPmOwlC08x8P8g',
    appId: '1:293546416514:android:92d97760e6ec2ba574179b',
    messagingSenderId: '293546416514',
    projectId: 'youssef-5228c',
    storageBucket: 'youssef-5228c.firebasestorage.app',
  );

  /// iOS Firebase configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvsWX4Ajo-LfKYMCp4rPmOwlC08x8P8g',
    appId: '1:293546416514:ios:92d97760e6ec2ba574179b',
    messagingSenderId: '293546416514',
    projectId: 'youssef-5228c',
    storageBucket: 'youssef-5228c.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID_HERE',
    iosBundleId: 'com.example.ecommerceApp',
  );

  /// macOS Firebase configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIvsWX4Ajo-LfKYMCp4rPmOwlC08x8P8g',
    appId: '1:293546416514:ios:92d97760e6ec2ba574179b',
    messagingSenderId: '293546416514',
    projectId: 'youssef-5228c',
    storageBucket: 'youssef-5228c.firebasestorage.app',
    iosClientId: 'YOUR_MACOS_CLIENT_ID_HERE',
    iosBundleId: 'com.example.ecommerceApp',
  );

  /// Windows Firebase configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIvsWX4Ajo-LfKYMCp4rPmOwlC08x8P8g',
    appId: '1:293546416514:web:92d97760e6ec2ba574179b',
    messagingSenderId: '293546416514',
    projectId: 'youssef-5228c',
    authDomain: 'youssef-5228c.firebaseapp.com',
    storageBucket: 'youssef-5228c.firebasestorage.app',
    measurementId: 'G-FDHWWLKL92',
  );
}
